site_name: 24Records

nav:
  - 主页:
    - index.md
    - Page 1: home/page-1.md
    - Page 2: home/page-2.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: squidfunk/mkdocs-material